---
title: "MATH60633 – TP2"
author: "William Delisle, Rémi Mailhot, Laurent Vienneau et Mathieu Verville"
date: '2023-04-19'
output:
  html_document: 
    toc: true
    toc_depth: 3
    toc_float: true
---

## Importation des données

```{r, warning = FALSE, include = FALSE}

# Import libraries & functions
library("PerformanceAnalytics")
library("here")

source(here("function", "f_eval_portfolio.R"))
source(here("function", "f_price_simul_univariate.R"))
source(here("function", "f_price_simul_bivariate.R"))
source(here("function", "f_price_simul_copula.R"))
source(here("function", "f_price_simul_complete.R"))
source(here("function", "f_price_simul_surface.R"))
source(here("function", "f_VaR_ES_PL.R"))
source(here("function", "f_plot_pdf.R"))
```

```{r, warning = FALSE}

# Load data
load(file = here("Data", "Market.rda"))

SP500_prices <- Market$sp500  
VIX_index    <- Market$vix
int_rate     <- Market$rf
call_info    <- Market$calls
put_info     <- Market$puts

```

## Fixation du prix d'un portefeuille d'options

```{r, warning = FALSE}

# Option portfolio description
last_price <- last(SP500_prices)
last_vol   <- last(VIX_index)
last       <- c(last_price, last_vol)
portfolio  <- list(Qty     = c(1, 1, 1, 1),
                   Strike  = c(1600, 1650, 1750, 1800),
                   tau     = c(20, 20, 40, 40),
                   is_call = rep(TRUE, 4))

# Evaluate portfolio value
init_value <- f_eval_portfolio(last, portfolio, int_rate)
cat("The initial value of the portfolio is :",sprintf("%f", init_value), "$\n")
```

## Un facteur de risque et un modèle gaussien

```{r, warning = FALSE}

# Calculate log returns for S&P500
rets <- CalculateReturns(SP500_prices, method = "log")
rets <- rets[-1,]

# Inputs for simulating prices
d_simul    <- 5
n_simul    <- 10000
price_init <- last_price

# Price simulation in 5 days
price_simul <- f_price_simul_univariate(rets, price_init, d_simul, n_simul)

# Option prices in 5 days from simulated prices
last              <- cbind(price_simul, rep(last_vol, n_simul))
option_simul_uni  <- apply(X         = last, 
                           MARGIN    = 1, 
                           FUN       = f_eval_portfolio, 
                           portfolio = portfolio, 
                           int_rate  = int_rate, 
                           d_simul   = d_simul)

# Compute VaR95, ES95 and P&L
result_uni <- f_VaR_ES_PL(init_value, option_simul_uni, level = 0.95)

# Result for risk mesure
cat("With the univariate Gaussian model : \n",
    "VaR at 95% is",sprintf("%f", result_uni$VaR), "$\n",
    "ES  at 95% is",sprintf("%f", result_uni$ES), "$\n")
```

```{r, warning = FALSE}

# P&L distribution
f_plot_pdf(result_uni, model = "Univariate Model")
```

```{r, include = FALSE}

# Save previous plot
f_png_save(result_uni, model = "Univariate Model", file_name = "univariate_distribution")
```

## Deux facteurs de risque et modèle gaussien

```{r, warning = FALSE}

# Calculate log returns for S&P500 & VIX
rets_SP500 <- rets
rets_VIX   <- CalculateReturns(VIX_index, method = "log")
rets_VIX   <- rets_VIX[-1,]
rets       <- data.frame(rets_SP500, rets_VIX)

# Simulating prices for S&P500 and VIX
price_init     <- c(last_price, last_vol)
price_simul_bi <- f_price_simul_bivariate(rets, price_init, d_simul, n_simul) 

# Option prices in 5 days from simulated prices
option_simul_bi <- apply(X         = price_simul_bi, 
                         MARGIN    = 1, 
                         FUN       = f_eval_portfolio, 
                         portfolio = portfolio, 
                         int_rate  = int_rate, 
                         d_simul   = d_simul)

# Compute VaR95, ES95 and P&L
result_bi <- f_VaR_ES_PL(init_value, option_simul_bi, level = 0.95)

# Result for risk mesure
cat("With the bivariate Gaussian model : \n",
    "VaR at 95% is",sprintf("%f", result_bi$VaR), "$\n",
    "ES  at 95% is",sprintf("%f", result_bi$ES), "$\n")
```

```{r, warning = FALSE}

# P&L distribution
f_plot_pdf(result_bi, model = "Bivariate Model")
```

```{r, include = FALSE}

# Save previous plot
f_png_save(result_bi, model = "Bivariate Model", file_name = "bivariate_distribution")
```

## Deux facteurs de risque et modèle copule-marginal

```{r, warning = FALSE}

# Simulating prices for S&P500 and VIX
nu              <- c(10, 5)
price_simul_cop <- f_price_simul_copula(rets, nu, price_init, d_simul, n_simul)

# Option prices in 5 days from simulated prices
option_simul_cop <- apply(X         = price_simul_cop, 
                          MARGIN    = 1, 
                          FUN       = f_eval_portfolio, 
                          portfolio = portfolio, 
                          int_rate  = int_rate, 
                          d_simul   = d_simul)

# Compute VaR95, ES95 and P&L
result_cop <- f_VaR_ES_PL(init_value, option_simul_cop, level = 0.95)

# Result for risk mesure
cat("With the Gaussian copula and Student marginals : \n",
    "VaR at 95% is",sprintf("%f", result_cop$VaR), "$\n",
    "ES  at 95% is",sprintf("%f", result_cop$ES), "$\n")
```

```{r, warning = FALSE}

# P&L distribution
f_plot_pdf(result_cop, model = "Copula Model")
```

```{r, include = FALSE}

# Save previous plot
f_png_save(result_cop, model = "Copula Model", file_name = "copula")
```

## Surface de volatilité

```{r, warning = FALSE}

# Option info + fit volatility surface + adjust vol simulation from las method
option_info      <- f_option_info(call_info, put_info, last_price)
alpha            <- f_opt_alpha(option_info)

# Simulating prices for VIX (we keep the copula simulation for S&P500)
price_simul_surf  <- f_price_simul_vol(alpha, last_vol, price_simul_cop, portfolio, d_simul)

# Option prices in 5 days from simulated prices
option_simul_surf <- apply(X         = price_simul_surf, 
                           MARGIN    = 1, 
                           FUN       = f_eval_portfolio, 
                           portfolio = portfolio, 
                           int_rate  = int_rate, 
                           d_simul   = d_simul)

# Compute VaR95, ES95 and P&L
vol_param_init  <- f_init_vol_param(alpha, price_init, portfolio)
last_surf       <- c(as.numeric(last_price), vol_param_init)
init_value_surf <- f_eval_portfolio(last_surf, portfolio, int_rate)
result_surf     <- f_VaR_ES_PL(init_value_surf, option_simul_surf, level = 0.95)

# Result for risk mesure
cat("With the Parametric Volatility Surface Model: \n",
    "VaR at 95% is",sprintf("%f", result_surf$VaR), "$\n",
    "ES  at 95% is",sprintf("%f", result_surf$ES), "$\n")

```

```{r, warning = FALSE}

# P&L distribution
f_plot_pdf(result_surf, model = "Parametric Volatility Surface Model")
```

```{r, include = FALSE}

# Save previous plot
f_png_save(result_surf, model = "Parametric Volatility Surface Model", file_name = "vol_surface")
```

## Approche complète

```{r, warning = FALSE}

# Simulating prices for S&P500 and VIX
price_simul_compl <- f_price_simul_complete(rets, price_init, d_simul, n_simul)

# Option prices in 5 days from simulated prices
option_simul_compl <- apply(X         = price_simul_compl, 
                            MARGIN    = 1, 
                            FUN       = f_eval_portfolio, 
                            portfolio = portfolio, 
                            int_rate  = int_rate, 
                            d_simul   = d_simul)

# Compute VaR95, ES95 and P&L
result_compl <- f_VaR_ES_PL(init_value, option_simul_compl, level = 0.95)

# Result for risk mesure
cat("With the Gaussian copula and Student marginals : \n",
    "VaR at 95% is",sprintf("%f", result_compl$VaR), "$\n",
    "ES  at 95% is",sprintf("%f", result_compl$ES), "$\n")

```

```{r, warning = FALSE}

# P&L distribution
f_plot_pdf(result_compl, model = "Complete Model")
```

```{r, include = FALSE}

# Save previous plot
f_png_save(result_compl, model = "Complete Model", file_name = "complete")
```
